########################################################################################
###               Export to Cytoscape                                         ##########
########################################################################################
setwd("/media/ducdo/UUI/Bioinformatics/Summer Research/Cancer_Survival/encRNA_methylation_260616")
source("/media/ducdo/UUI/Bioinformatics/Summer Research/Cancer_Survival/encRNA_methylation_260616/code_correlation_analysis/helper_functions.R")
source("/media/ducdo/UUI/Bioinformatics/Summer Research/Cancer_Survival/encRNA_methylation_260616/code_network_construction/network_helper_functions.R")

require(igraph); require(RCy3); require(plyr); require(dplyr); require(data.table)

load("data_Saved_R_Objects/miRNA_target/predicted_normal_tumor_goodCorr.rda")

normal_encRNA_graph = build_iGraph(df = normal_encRNA_sensitivity_bound_goodCoor)
tumor_encRNA_graph = build_iGraph(df = tumor_encRNA_sensitivity_bound_goodCoor)

# select graphs
graph_encRNA = normal_encRNA_graph
encRNA_df= normal_encRNA_sensitivity_bound_goodCoor[, c("lncRNA","mRNA", "sensitivity")]
encRNA_df$pair = paste(encRNA_df$mRNA, "~", encRNA_df$lncRNA, sep = "") # this is for later to be compared with the pair generated by Cytoscape

# check multiple edges
vcount(graph_encRNA)
E(graph_encRNA)[which_multiple(graph_encRNA,  eids = E(graph_encRNA))]

# create graph_nel object
graphNel_obj <- igraph::as_graphnel(graph_encRNA); gc()

#save(graphNel_obj, file = "graphNel_obj.rda")
# check to see 
graph::nodeData(graphNel_obj, igraph::V(graph_encRNA)$name, 'color')
graph::nodeData(graphNel_obj, igraph::V(graph_encRNA)$name, 'type')
graph::edgeData(graphNel_obj, 
                as.character(encRNA_df$lncRNA), 
                as.character(encRNA_df$mRNA),
                'weight')

# init attributes
graphNel_obj <- RCy3::initNodeAttribute(graphNel_obj, 'color', 'char', 'a') 
graphNel_obj <- RCy3::initNodeAttribute(graphNel_obj, 'type', 'char', 'a') 
graphNel_obj <- RCy3::initEdgeAttribute (graphNel_obj, "weight", 'numeric', 0)

# Next, we will create a new graph window in cytoscape
# cytoscape_window <- RCy3::CytoscapeWindow("encRNA_normal", graph = graphNel_obj, overwriteWindow = TRUE)
cytoscape_window <- RCy3::CytoscapeWindow("encRNA_normal", graph = graphNel_obj, overwriteWindow = TRUE)

# We can display graph, with defaults color/size scheme
RCy3::displayGraph(cytoscape_window)

# set node and edge attributes
RCy3::setNodeAttributesDirect(cytoscape_window, 'type', 'char', 
                              igraph::V(graph_encRNA)$name, 
                              igraph::V(graph_encRNA)$type)
RCy3::setNodeAttributesDirect(cytoscape_window, 'color', 'char', 
                              igraph::V(graph_encRNA)$name, 
                              igraph::V(graph_encRNA)$color)

edge_names = names(RCy3::cy2.edge.names (cytoscape_window@graph))

# test$pair = as.factor(test$pair)
# test$pair = gdata::reorder.factor(test$pair, new.order=edge_names)
# test %>% dplyr::arrange(pair)
encRNA_df = encRNA_df[match(edge_names, encRNA_df$pair),]

RCy3::setEdgeAttributesDirect(obj = cytoscape_window, 
                              attribute.name = 'weight', 
                              attribute.type = 'numeric', 
                              edge.names = as.character (RCy3::cy2.edge.names (cytoscape_window@graph)), 
                              values = encRNA_df$sensitivity)


# If you also want to choose a layout from R, a list  of available layouts can be accessed as follow:
cy <- RCy3::CytoscapeConnection()
hlp <-RCy3::getLayoutNames(cy)
# hlp
# [1] "attribute-circle"      "stacked-node-layout"   "degree-circle"         "circular"              "attributes-layout"     "kamada-kawai"         
# [7] "force-directed"        "grid"                  "hierarchical"          "fruchterman-rheingold" "isom"      
# We'll select the "fruchterman-rheingold" layout. This layout is the layout number 10 
# To see properties for the given layout, use:
# RCy3::getLayoutPropertyNames(cy, hlp[10])
# We can choose any property we want and provide them as a list
#RCy3::setLayoutProperties (cytoscape_window, hlp[10], list (gravity_multiplier = 'similarity', nIterations = 1))
RCy3::setLayoutProperties (cytoscape_window, hlp[10], list (gravity_multiplier = 'similarity', nIterations = 1))
RCy3::layoutNetwork(cytoscape_window, hlp[10])

RCy3::setDefaultNodeSize(cytoscape_window, 50)
RCy3::setDefaultNodeFontSize(cytoscape_window, 60)


######################################################################################

# select graphs
graph_encRNA = tumor_encRNA_graph
encRNA_df= tumor_encRNA_sensitivity_bound_goodCoor[, c("lncRNA","mRNA", "sensitivity")]
encRNA_df$pair = paste(encRNA_df$mRNA, "~", encRNA_df$lncRNA, sep = "") # this is for later to be compared with the pair generated by Cytoscape

# check multiple edges
vcount(graph_encRNA)
E(graph_encRNA)[which_multiple(graph_encRNA,  eids = E(graph_encRNA))]

# create graph_nel object
graphNel_obj2 <- igraph::as_graphnel(graph_encRNA); gc()

#save(graphNel_obj, file = "graphNel_obj.rda")
# check to see 
graph::nodeData(graphNel_obj2, igraph::V(graph_encRNA)$name, 'color')
graph::nodeData(graphNel_obj2, igraph::V(graph_encRNA)$name, 'type')
graph::edgeData(graphNel_obj2, 
                as.character(encRNA_df$lncRNA), 
                as.character(encRNA_df$mRNA),
                'weight')

# init attributes
graphNel_obj2 <- RCy3::initNodeAttribute(graphNel_obj2, 'color', 'char', 'a') 
graphNel_obj2 <- RCy3::initNodeAttribute(graphNel_obj2, 'type', 'char', 'a') 
graphNel_obj2 <- RCy3::initEdgeAttribute (graphNel_obj2, "weight", 'numeric', 0)

# Next, we will create a new graph window in cytoscape
# cytoscape_window <- RCy3::CytoscapeWindow("encRNA_normal", graph = graphNel_obj, overwriteWindow = TRUE)
cytoscape_window2 <- RCy3::CytoscapeWindow("encRNA_tumor", graph = graphNel_obj2, overwriteWindow = FALSE)

# We can display graph, with defaults color/size scheme
RCy3::displayGraph(cytoscape_window2)

# set node and edge attributes
RCy3::setNodeAttributesDirect(cytoscape_window2, 'type', 'char', 
                              igraph::V(graph_encRNA)$name, 
                              igraph::V(graph_encRNA)$type)
RCy3::setNodeAttributesDirect(cytoscape_window2, 'color', 'char', 
                              igraph::V(graph_encRNA)$name, 
                              igraph::V(graph_encRNA)$color)

edge_names = names(RCy3::cy2.edge.names (cytoscape_window2@graph))

# test$pair = as.factor(test$pair)
# test$pair = gdata::reorder.factor(test$pair, new.order=edge_names)
# test %>% dplyr::arrange(pair)
encRNA_df = encRNA_df[match(edge_names, encRNA_df$pair),]

RCy3::setEdgeAttributesDirect(obj = cytoscape_window2, 
                              attribute.name = 'weight', 
                              attribute.type = 'numeric', 
                              edge.names = as.character (RCy3::cy2.edge.names (cytoscape_window2@graph)), 
                              values = encRNA_df$sensitivity)


# If you also want to choose a layout from R, a list  of available layouts can be accessed as follow:
cy <- RCy3::CytoscapeConnection()
hlp <-RCy3::getLayoutNames(cy)
# hlp
# [1] "attribute-circle"      "stacked-node-layout"   "degree-circle"         "circular"              "attributes-layout"     "kamada-kawai"         
# [7] "force-directed"        "grid"                  "hierarchical"          "fruchterman-rheingold" "isom"      
# We'll select the "fruchterman-rheingold" layout. This layout is the layout number 10 
# To see properties for the given layout, use:
# RCy3::getLayoutPropertyNames(cy, hlp[10])
# We can choose any property we want and provide them as a list
#RCy3::setLayoutProperties (cytoscape_window, hlp[10], list (gravity_multiplier = 'similarity', nIterations = 1))
RCy3::setLayoutProperties (cytoscape_window2, hlp[10], list (gravity_multiplier = 'similarity', nIterations = 1))
RCy3::layoutNetwork(cytoscape_window2, hlp[10])

RCy3::setDefaultNodeSize(cytoscape_window2, 20)
RCy3::setDefaultNodeFontSize(cytoscape_window2, 20)




